<a href="https://colab.research.google.com/github/vika3mm/gost_progect/blob/main/%D0%BE%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_layout3_2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade pip setuptools wheel
!pip install --no-build-isolation seqeval

Requirement already satisfied: pip in /usr/local/lib/python3.13/dist-packages (26.2.1)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (84.0.0)
Requirement already satisfied: wheel in /usr/local/lib/python3.13/dist-packages (0.48.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.13/dist-packages (from wheel) (26.3)
Requirement already satisfied: seqeval in /usr/local/lib/python3.13/dist-packages (0.0.10)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from seqeval) (2.1.3)
Requirement already satisfied: Keras>=2.2.4 in /usr/local/lib/python3.13/dist-packages (from seqeval) (3.13.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (0.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (26.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from optree->Keras>=2.2.4->seqeval) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->Keras>=2.2.4->seqeval) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->Keras>=2.2.4->seqeval) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->Keras>=2.2.4->seqeval) (0.1.2)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import json
import os
import random
import numpy as np
import torch
from PIL import Image
from sklearn.model_selection import train_test_split
from datasets import Dataset
from transformers import (
    LayoutLMv3Processor,
    LayoutLMv3ForTokenClassification,
    TrainingArguments,
    Trainer
)

print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

Mounted at /content/drive
False

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
DATASET_PATH = "/content/drive/MyDrive/GOST_Project/layoutlm_dataset_2.json"
IMAGES_DIR = "/content/drive/MyDrive/GOST_Project/общие_фото_новинка"
MODEL_OUTPUT = "/content/drive/MyDrive/GOST_Project/layoutlm_model_split"

# Путь для нового датасета (разбитого на части)
SPLIT_DATASET_PATH = "/content/drive/MyDrive/GOST_Project/layoutlm_dataset_split.json"

In [ ]:
with open(DATASET_PATH, "r", encoding="utf-8") as f:
    data = json.load(f)

print("Страниц в исходном датасете:", len(data))

labels = sorted(
    list(
        set(
            word["label"]
            for page in data
            for word in page["words"]
        )
    )
)
print("Метки:", labels)
print("Количество меток:", len(labels))

label2id = {label: i for i, label in enumerate(labels)}
id2label = {i: label for label, i in label2id.items()}
print(label2id)

Страниц в исходном датасете: 327
Метки: ['BODY', 'FIGURE', 'FIGURE_CAPTION', 'FOOTNOTE', 'FORMULA', 'OTHER', 'REFERENCE', 'SECTION_HEADER', 'TABLE', 'TABLE_CAPTION', 'TITLE', 'TOC']
Количество меток: 12
{'BODY': 0, 'FIGURE': 1, 'FIGURE_CAPTION': 2, 'FOOTNOTE': 3, 'FORMULA': 4, 'OTHER': 5, 'REFERENCE': 6, 'SECTION_HEADER': 7, 'TABLE': 8, 'TABLE_CAPTION': 9, 'TITLE': 10, 'TOC': 11}

In [ ]:
MAX_WORDS_PER_CHUNK = 400

def split_long_pages(data, max_words=MAX_WORDS_PER_CHUNK):
    """
    Разбивает длинные страницы на части.
    Каждая часть становится отдельным примером.
    """
    split_data = []
    total_original = len(data)
    total_split = 0

    for page in data:
        words = page["words"]
        image_name = page["image"]

        if len(words) <= max_words:
            # Страница короткая — оставляем как есть
            split_data.append({
                "image": image_name,
                "words": words
            })
            total_split += 1
        else:
            # Страница длинная — режем на части
            num_chunks = (len(words) + max_words - 1) // max_words
            for i in range(num_chunks):
                start = i * max_words
                end = min((i + 1) * max_words, len(words))
                chunk_words = words[start:end]

                split_data.append({
                    "image": image_name,
                    "words": chunk_words,
                    "chunk_index": i,
                    "chunk_total": num_chunks
                })
                total_split += 1

    print(f"Исходных страниц: {total_original}")
    print(f"После разбиения: {total_split}")
    print(f"Добавлено частей: {total_split - total_original}")
    return split_data

split_data = split_long_pages(data, max_words=MAX_WORDS_PER_CHUNK)

Исходных страниц: 327
После разбиения: 327
Добавлено частей: 0

In [ ]:
with open(SPLIT_DATASET_PATH, "w", encoding="utf-8") as f:
    json.dump(split_data, f, ensure_ascii=False)

print(f"Сохранено: {SPLIT_DATASET_PATH}")
print(f"Всего примеров: {len(split_data)}")

Сохранено: /content/drive/MyDrive/GOST_Project/layoutlm_dataset_split.json
Всего примеров: 327

In [ ]:
import re

def get_document_name(image_name):
    """
    Извлекает имя документа из имени файла.
    Пример: 'alekseeva_e_a_page_1.png' -> 'alekseeva_e_a'
    """
    # Убираем расширение
    name = os.path.splitext(image_name)[0]
    # Убираем '_page_N' в конце
    name = re.sub(r'_page_\d+$', '', name)
    return name

# Собираем уникальные документы
documents = {}
for item in split_data:
    doc_name = get_document_name(item["image"])
    if doc_name not in documents:
        documents[doc_name] = []
    documents[doc_name].append(item)

doc_names = sorted(documents.keys())
print(f"Уникальных документов: {len(doc_names)}")
print(doc_names[:10])

train_docs, test_docs = train_test_split(
    doc_names, test_size=0.15, random_state=42
)
train_docs, val_docs = train_test_split(
    train_docs, test_size=0.15, random_state=42
)

print(f"Train документов: {len(train_docs)}")
print(f"Val документов: {len(val_docs)}")
print(f"Test документов: {len(test_docs)}")

train_data = [item for doc in train_docs for item in documents[doc]]
val_data = [item for doc in val_docs for item in documents[doc]]
test_data = [item for doc in test_docs for item in documents[doc]]

print(f"Train примеров: {len(train_data)}")
print(f"Val примеров: {len(val_data)}")
print(f"Test примеров: {len(test_data)}")

Уникальных документов: 19
['alekseeva_e_a', 'tohtueva_e_a', 'trubacheva_v_p', 'Анисимова_текст', 'Багрянова_текст', 'Вихорев_Текст', 'Воробьев_ТекстВКР', 'Габитов_диплом', 'Гащенко_диплом', 'Головин_диплом']
Train документов: 13
Val документов: 3
Test документов: 3
Train примеров: 175
Val примеров: 86
Test примеров: 66

In [ ]:
processor = LayoutLMv3Processor.from_pretrained(
    "microsoft/layoutlmv3-base",
    apply_ocr=False
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
def normalize_bbox(bbox, width, height):
    return [
        int(1000 * bbox[0] / width),
        int(1000 * bbox[1] / height),
        int(1000 * bbox[2] / width),
        int(1000 * bbox[3] / height),
    ]

def prepare_examples(pages):
    dataset = []
    for page in pages:
        image_path = os.path.join(IMAGES_DIR, page["image"])
        image = Image.open(image_path).convert("RGB")
        width, height = image.size

        words = []
        boxes = []
        labels = []

        for word in page["words"]:
            words.append(word["text"])
            boxes.append(normalize_bbox(word["bbox"], width, height))
            labels.append(label2id[word["label"]])

        dataset.append({
            "image": image,
            "words": words,
            "boxes": boxes,
            "labels": labels
        })
    return dataset

train_examples = prepare_examples(train_data)
val_examples = prepare_examples(val_data)
test_examples = prepare_examples(test_data)

print(len(train_examples))
print(len(val_examples))
print(len(test_examples))

175
86
66

In [ ]:
def encode_example(example):
    encoding = processor(
        images=example["image"],
        text=example["words"],
        boxes=example["boxes"],
        word_labels=example["labels"],
        truncation=True,
        padding="max_length",
        max_length=512,
        return_tensors="pt"
    )
    encoding = {k: v.squeeze() for k, v in encoding.items()}
    return encoding

train_ds = Dataset.from_list(train_examples)
val_ds = Dataset.from_list(val_examples)
test_ds = Dataset.from_list(test_examples)

print(train_ds)

train_ds = train_ds.map(encode_example, remove_columns=train_ds.column_names)
val_ds = val_ds.map(encode_example, remove_columns=val_ds.column_names)
test_ds = test_ds.map(encode_example, remove_columns=test_ds.column_names)

print(train_ds)

Dataset({
    features: ['image', 'words', 'boxes', 'labels'],
    num_rows: 175
})

Map:   0%|          | 0/175 [00:00<?, ? examples/s]

Map:   0%|          | 0/86 [00:00<?, ? examples/s]

Map:   0%|          | 0/66 [00:00<?, ? examples/s]

Dataset({
    features: ['labels', 'input_ids', 'attention_mask', 'bbox', 'pixel_values'],
    num_rows: 175
})

In [ ]:
model = LayoutLMv3ForTokenClassification.from_pretrained(
    "microsoft/layoutlmv3-base",
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

Loading weights:   0%|          | 0/212 [00:00<?, ?it/s]

[transformers] LayoutLMv3ForTokenClassification LOAD REPORT from: microsoft/layoutlmv3-base
Key                        | Status  |
---------------------------+---------+-
classifier.dense.bias      | MISSING |
classifier.dense.weight    | MISSING |
classifier.out_proj.bias   | MISSING |
classifier.out_proj.weight | MISSING |

Notes:
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [ ]:
!pip show seqeval

Name: seqeval
Version: 0.0.10
Summary: Testing framework for sequence labeling
Home-page: https://github.com/chakki-works/seqeval
Author: Hironsan
Author-email: hiroki.nakayama.py@gmail.com
License: MIT
Location: /usr/local/lib/python3.13/dist-packages
Requires: Keras, numpy
Required-by:

In [ ]:
!pip install --upgrade --no-build-isolation seqeval

Requirement already satisfied: seqeval in /usr/local/lib/python3.13/dist-packages (0.0.10)
Collecting seqeval
  Using cached seqeval-1.2.2.tar.gz (43 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/9d/2d/233c79d5b4e5ab1dbf111242299153f3caddddbb691219f363ad55ce783d/seqeval-1.2.2.tar.gz has inconsistent version: expected '1.2.2', but metadata has '0.0.0'
  Using cached seqeval-1.2.1.tar.gz (43 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/c4/47/f85f522f1f2532ca650474088e4024a9f52d524379bff058eaadf53cb663/seqeval-1.2.1.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/c4/47/f85f522f1f2532ca650474088e4024a9f52d524379bff058eaadf53cb663/seqeval-1.2.1.tar.gz has inconsistent version: expected '1.2.1', but metadata has '0.0.0'
  Using cached seqeval-1.2.0.tar.gz (42 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/be/cd/d467b26ee460ff69c04e225c3bc7ea97ade4dc43c6982bac99ff032bb3e1/seqeval-1.2.0.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/be/cd/d467b26ee460ff69c04e225c3bc7ea97ade4dc43c6982bac99ff032bb3e1/seqeval-1.2.0.tar.gz has inconsistent version: expected '1.2.0', but metadata has '0.0.0'
  Using cached seqeval-1.1.1.tar.gz (40 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/ba/7d/4bf58a9ac8cf69d24a388eb44f25d713c9a66ee9abaacb929aa5be0bbd36/seqeval-1.1.1.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/ba/7d/4bf58a9ac8cf69d24a388eb44f25d713c9a66ee9abaacb929aa5be0bbd36/seqeval-1.1.1.tar.gz has inconsistent version: expected '1.1.1', but metadata has '0.0.0'
  Using cached seqeval-1.1.0.tar.gz (37 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/bc/6c/71a5ca457851287ceba1c969bfb21f46ffdae7dfae1fa30456ef4bdc6412/seqeval-1.1.0.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/bc/6c/71a5ca457851287ceba1c969bfb21f46ffdae7dfae1fa30456ef4bdc6412/seqeval-1.1.0.tar.gz has inconsistent version: expected '1.1.0', but metadata has '0.0.0'
  Using cached seqeval-1.0.0.tar.gz (36 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/75/63/180f7556bfd9b0f89bc853ee46d01a3a611d74798230a930afac6873d15c/seqeval-1.0.0.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/75/63/180f7556bfd9b0f89bc853ee46d01a3a611d74798230a930afac6873d15c/seqeval-1.0.0.tar.gz has inconsistent version: expected '1.0.0', but metadata has '0.0.0'
  Using cached seqeval-0.0.19.tar.gz (30 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/93/e5/b7705156a77f742cfe4fc6f22d0c71591edb2d243328dff2f8fc0f933ab6/seqeval-0.0.19.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/93/e5/b7705156a77f742cfe4fc6f22d0c71591edb2d243328dff2f8fc0f933ab6/seqeval-0.0.19.tar.gz has inconsistent version: expected '0.0.19', but metadata has '0.0.0'
  Using cached seqeval-0.0.18.tar.gz (20 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/bb/e6/0ccf683d190049f2c0311281c303756d1e62d0676ac0a88b45ec86bf1ca9/seqeval-0.0.18.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/bb/e6/0ccf683d190049f2c0311281c303756d1e62d0676ac0a88b45ec86bf1ca9/seqeval-0.0.18.tar.gz has inconsistent version: expected '0.0.18', but metadata has '0.0.0'
  Using cached seqeval-0.0.17.tar.gz (20 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/d8/9d/89d9ac5d6506f8368ba5ae53b054cf26bf796935eff6a1945431c7a5d485/seqeval-0.0.17.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/d8/9d/89d9ac5d6506f8368ba5ae53b054cf26bf796935eff6a1945431c7a5d485/seqeval-0.0.17.tar.gz has inconsistent version: expected '0.0.17', but metadata has '0.0.0'
  Using cached seqeval-0.0.16.tar.gz (20 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/0c/f4/08d3d249926e38f06f514976022495fa01aeed5d02341125a67736bd2052/seqeval-0.0.16.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/0c/f4/08d3d249926e38f06f514976022495fa01aeed5d02341125a67736bd2052/seqeval-0.0.16.tar.gz has inconsistent version: expected '0.0.16', but metadata has '0.0.0'
  Using cached seqeval-0.0.15.tar.gz (20 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/80/ab/02821aa982f1cf1bc2a18e9997d8fcf204534d74646e25aa51196c50da8e/seqeval-0.0.15.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/80/ab/02821aa982f1cf1bc2a18e9997d8fcf204534d74646e25aa51196c50da8e/seqeval-0.0.15.tar.gz has inconsistent version: expected '0.0.15', but metadata has '0.0.0'
  Using cached seqeval-0.0.13.tar.gz (20 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/61/fa/c1c87e39572550ae8794a7f0209e2a08301ea28c8cd1deb1204ec8609ecb/seqeval-0.0.13.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/61/fa/c1c87e39572550ae8794a7f0209e2a08301ea28c8cd1deb1204ec8609ecb/seqeval-0.0.13.tar.gz has inconsistent version: expected '0.0.13', but metadata has '0.0.0'
  Using cached seqeval-0.0.12.tar.gz (21 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/34/91/068aca8d60ce56dd9ba4506850e876aba5e66a6f2f29aa223224b50df0de/seqeval-0.0.12.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/34/91/068aca8d60ce56dd9ba4506850e876aba5e66a6f2f29aa223224b50df0de/seqeval-0.0.12.tar.gz has inconsistent version: expected '0.0.12', but metadata has '0.0.0'
  Using cached seqeval-0.0.11.tar.gz (21 kB)
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/d6/85/dd7bd498196e02fce41b696ceae294204e11586eedf718459c45dbf0e120/seqeval-0.0.11.tar.gz (from https://pypi.org/simple/seqeval/): Requested seqeval from https://files.pythonhosted.org/packages/d6/85/dd7bd498196e02fce41b696ceae294204e11586eedf718459c45dbf0e120/seqeval-0.0.11.tar.gz has inconsistent version: expected '0.0.11', but metadata has '0.0.0'
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.13/dist-packages (from seqeval) (2.1.3)
Requirement already satisfied: Keras>=2.2.4 in /usr/local/lib/python3.13/dist-packages (from seqeval) (3.13.2)
Requirement already satisfied: absl-py in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (1.4.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (0.20.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (0.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from Keras>=2.2.4->seqeval) (26.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from optree->Keras>=2.2.4->seqeval) (4.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->Keras>=2.2.4->seqeval) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->Keras>=2.2.4->seqeval) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->Keras>=2.2.4->seqeval) (0.1.2)

In [ ]:
from seqeval.metrics import classification_report, precision_score, recall_score, f1_score

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = []
    true_labels = []

    for pred, lab in zip(predictions, labels):
        cur_preds = []
        cur_labels = []
        for p_i, l_i in zip(pred, lab):
            if l_i == -100:
                continue
            cur_preds.append(id2label[p_i])
            cur_labels.append(id2label[l_i])
        true_predictions.append(cur_preds)
        true_labels.append(cur_labels)

    return {
        "precision": precision_score(true_labels, true_predictions),
        "recall": recall_score(true_labels, true_predictions),
        "f1": f1_score(true_labels, true_predictions),
        "accuracy": None,  # seqeval не даёт accuracy напрямую
    }

In [ ]:
training_args = TrainingArguments(
    output_dir=MODEL_OUTPUT,
    learning_rate=2e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=15,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    logging_steps=10,
    save_total_limit=2,
    fp16=True
)

In [ ]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_ds,
    eval_dataset=val_ds,
    compute_metrics=compute_metrics
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=1320, training_loss=0.17539189979292905, metrics={'train_runtime': 2484.2548, 'train_samples_per_second': 1.057, 'train_steps_per_second': 0.531, 'total_flos': 696757565952000.0, 'train_loss': 0.17539189979292905, 'epoch': 15.0})

In [ ]:
trainer.save_model(MODEL_OUTPUT)
processor.save_pretrained(MODEL_OUTPUT)
print(f"Модель сохранена: {MODEL_OUTPUT}")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Модель сохранена: /content/drive/MyDrive/GOST_Project/layoutlm_model_split

In [ ]:
metrics = trainer.evaluate(test_ds)
print(metrics)

{'eval_loss': 0.6389191150665283, 'eval_precision': 0.946058091286307, 'eval_recall': 0.8620037807183365, 'eval_f1': 0.9020771513353116, 'eval_accuracy': None}

In [ ]:
print(trainer.state.best_model_checkpoint)